# Generated by Django 5.1.4 on 2024-12-11 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('brigade_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Locomotive',
            fields=[
                ('registration_number', models.AutoField(primary_key=True, serialize=False)),
                ('depot', models.CharField(max_length=50)),
                ('locomotive_type', models.CharField(choices=[('вантажний', 'вантажний'), ('пасажирський', 'пасажирський')], max_length=50)),
                ('manufacture_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('repair_id', models.AutoField(primary_key=True, serialize=False)),
                ('repair_type', models.CharField(choices=[('поточний', 'поточний'), ('технічне обслуговування', 'технічне обслуговування'), ('позаплановий', 'позаплановий')], max_length=50)),
                ('start_date', models.DateField()),
                ('repair_days', models.PositiveIntegerField()),
                ('daily_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.brigade')),
                ('locomotive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.locomotive')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('birth_date', models.DateField()),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.brigade')),
            ],
        ),
    ]
